const jwt = require("jsonwebtoken");
const { SECRET } = require("../config");

module.exports = (req, res, next) => {
  if (req.method === "OPTIONS") next();

  try {
    const token = req.get("Authorization").split(" ")[1];
    if (!token) return res.status(403).send("User not authorized");

    jwt.verify(token, SECRET); //check if this token is generated by our server

    next();
  } catch (error) {
    res.status(403).send("User not authorized");
  }
};
